name: "Check Pull Request Review Comments"
description: "Check that PR comment has minimum length."
branding:
  icon: message-square
  color: purple

inputs:
  comments-must-contain:
    description: "This text must appear in a pull request review comments. Ignore cases"
    required: true
    default: ""

runs:
  using: 'node16'
  main: 'dist/index.js'
